export const SET_USER_FILTER = 'SET_USER_FILTER'
export const SET_GENDER_FILTER = 'SET_GENDER_FILTER'
export const SET_FILTER_DISABLED = 'SET_FILTER_DISABLED'
export const SET_FILTER_ENABLED = 'SET_FILTER_ENABLED'