export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_USER_JOB = 'SET_USER_JOB'
export const SET_USER_ADDR = 'SET_USER_ADDR'
export const CREATE_USER = 'CREATE_USER'
export const GET_USER_LIST = 'GET_USER_LIST'
export const SET_USER_LIST = 'SET_USER_LIST'
export const CLEAR_USER = 'CLEAR_USER'
export const UPDATE_USER = 'UPDATE_USER'